version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - webapp

  webapp:
    build: src
    image: group-c/flask-app
    ports:
      - "8030:8030"
    environment: 
      S3_ACCESS_KEY: "WRITE_YOUR_ACCESS_KEY_HERE"
      S3_SECRET_ACCESS_KEY: "WRITE_YOUR_S3_SECRET_ACCESS_KEY_HERE"
    container_name: upload-image
 